CREATE TABLE Generator1 (
	StateID INTEGER UNSIGNED NOT NULL,
	CountyID INTEGER UNSIGNED NOT NULL,
	ZoneID INTEGER UNSIGNED NOT NULL,
	LinkID INTEGER UNSIGNED NOT NULL,
	Time DATETIME NOT NULL,
	VType INTEGER UNSIGNED NOT NULL,
	ActivityPerHour FLOAT
) Engine=MyISAM DEFAULT CHARSET='utf8mb4' COLLATE 'utf8mb4_unicode_ci';
